allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true

supportedArchitectures:
  os:
    - current
    - darwin
    - win32
  cpu:
    - current
    - arm64
    - x64

overrides:
  '@langchain/core': ^1.1.46
  '@langchain/langgraph': ^1.3.0
